name          'example42/mongodb'
version       '3.0.0'
source        'https://github.com/example42/puppet-mongodb'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages mongodb'
description   'This module installs and manages mongodb. Based of stdmod/puppet-skeleton-standard 0.0.3.'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
dependency    'ripienaar/module_data'
